[pytest]
addopts = --headed --browser chromium --html=reports/report_chrome.html --self-contained-html --slowmo=5000
testpaths = tests
markers =
    browser: browser tests
    smoke: smoke tests
    regression: regression tests
    demo: pytest learning/demo tests